# Installation Steps
1. conda activate pytorch_nlp_book
2. conda install pytorch torchvision -c pytorch

In [1]:
%load_ext watermark
import random
from sklearn.datasets import make_classification
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
%matplotlib inline 
import matplotlib.pyplot as plt
import torch
%watermark  -d -t -v -p numpy,pandas,matplotlib,sklearn,torch

2020-07-13 00:19:01 

CPython 3.8.3
IPython 7.13.0

numpy 1.18.1
pandas 1.0.3
matplotlib 3.1.3
sklearn 0.22.1
torch 1.5.0


# Creating empty matrix

In [2]:
print(np.empty(5))
print(torch.empty(5))

[0.   0.25 0.5  0.75 1.  ]
tensor([0.0000e+00, -0.0000e+00, 0.0000e+00, -0.0000e+00, 1.1210e-44])


# Creating general matrices

In [3]:
# Ones Matrix
print(np.ones((5,3)))
print(torch.ones((5,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [4]:
# Zeros Matrix
print(np.zeros((5,3)))
print(torch.zeros((5,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
# Identity Matrix
print(np.eye(2))
print(torch.eye(2))

[[1. 0.]
 [0. 1.]]
tensor([[1., 0.],
        [0., 1.]])


# Creating tensor from python datatypes directly

In [6]:
print(np.array([1,2,3]))
print(torch.tensor([1,2,3]))

[1 2 3]
tensor([1, 2, 3])


# Creating random matrices

In [7]:
print(np.random.randn(2,3))
print(torch.randn(size = [2,3]))

[[-1.22512307  0.12075924 -0.69020433]
 [-1.41442814  0.03657385  1.88369779]]
tensor([[ 1.1502, -0.3289,  0.7004],
        [ 0.4600,  0.6454, -0.5006]])


# Converting a numpy array to tensor and vice versa

In [8]:
a = np.array([1,2,3])
t_a = torch.from_numpy(a)
print(t_a)
print(t_a.numpy())

tensor([1, 2, 3])
[1 2 3]


# Arithmetic Operations

In [9]:
np_x = np.array([1,2,3])
np_y = np.array([2,4,6])

torch_x = torch.from_numpy(np_x)
torch_y = torch.from_numpy(np_y)

print("Inputs : \n")
print("\tx = {} \n\ty = {}".format(np_x, np_y))

print("Addition : \n" )

np_z = np_x+np_y
print("\tNumpy: {}".format(np_z))

torch_z = torch.add(torch_x, torch_y)
print("\tTorch: {}".format(torch_z))


print("Subtraction : \n")

np_z = np_x-np_y
print("\tNumpy: {}".format(np_z))

torch_z = torch.sub(torch_x, torch_y)
print("\tTorch: {}".format(torch_z))


print("Element Wise Multiplication : \n")
np_z = np_x-np_y
print("\tNumpy: {}".format(np_z))

torch_z = torch_x*torch_y
print("\tTorch: {}".format(torch_z))


print("Matrix Multiplication : \n")
np_z = np.dot(np_x.reshape(-1,1).T, np_y.reshape(-1,1))
print("\tNumpy: {}".format(np_z))

torch_z = torch.mm(torch_x.view(-1,1).T, torch_y.view(-1,1))
print("\tTorch: {}".format(torch_z))

Inputs : 

	x = [1 2 3] 
	y = [2 4 6]
Addition : 

	Numpy: [3 6 9]
	Torch: tensor([3, 6, 9])
Subtraction : 

	Numpy: [-1 -2 -3]
	Torch: tensor([-1, -2, -3])
Element Wise Multiplication : 

	Numpy: [-1 -2 -3]
	Torch: tensor([ 2,  8, 18])
Matrix Multiplication : 

	Numpy: [[28]]
	Torch: tensor([[28]])


# Inplace operations

In [10]:
a = torch.tensor([1,2,3])
print(a)

# Note the underscore("_")
a.add_(1)
print(a)

tensor([1, 2, 3])
tensor([2, 3, 4])


# Numpy and pytorch tensors memory sharing

In [11]:
a = np.array([1,2,3])
print("Original Numpy array : \n\t{}\n".format(a))

t_a = torch.from_numpy(a)
print("Tensor Created from Numpy array : \n\t{}\n".format(t_a))


t_a.add_(1)
print("Tensor after addition : \n\t{}\n".format(t_a))


print("Numpy array after performing operation on tensor : \n\t{}\n".format(a))


Original Numpy array : 
	[1 2 3]

Tensor Created from Numpy array : 
	tensor([1, 2, 3])

Tensor after addition : 
	tensor([2, 3, 4])

Numpy array after performing operation on tensor : 
	[2 3 4]



# Moving data between GPU and CPU

In [12]:
if torch.cuda.is_available():
    print("Device Available : GPU")
else:
    print("Device Available : CPU")
device = "cuda" if torch.cuda.is_available() else "cpu"

Device Available : CPU


In [13]:
x = torch.tensor([1,2,3])
x = x.to(device)
x

tensor([1, 2, 3])

# Auto Grad
Specifying for which tensors gradients is required to calculated and setting this arguments tracks all operations on it.

In [14]:
a = torch.randn((2,2))
a.requires_grad

False

In [15]:
a = torch.randn((2,2), requires_grad=True)
a.requires_grad

True

In [16]:
a = torch.randn((2,2))
c = a*a
d = c+3
out = torch.mean(d)
print(out)

tensor(5.3525)


In [17]:
print(a.requires_grad, c.requires_grad, d.requires_grad, out.requires_grad)

False False False False


In [18]:
a = torch.randn((2,2))
a.requires_grad_(True)
c = a*a
d = c+3
out = torch.mean(d)
print(out)

tensor(4.6164, grad_fn=<MeanBackward0>)


In [19]:
print(a.requires_grad, c.requires_grad, d.requires_grad, out.requires_grad)

True True True True


In [20]:
torch.manual_seed(9)
a = torch.randn((2,2), requires_grad=True)
a.requires_grad_(True)
c = a*a
d = c+3
out = torch.mean(d)
print(out)

tensor(3.9570, grad_fn=<MeanBackward0>)


In [21]:
# Auto differentiation
out.backward()

# To Do : Add Latex
## dout/da = a/2; Jacobian matrix

In [22]:
a.grad # dout/da

tensor([[ 0.0224,  0.9556],
        [-0.1155,  0.1730]])

In [23]:
print(a/2 == a.grad)

tensor([[True, True],
        [True, True]])


In [24]:
c, c.detach()

(tensor([[2.0006e-03, 3.6528e+00],
         [5.3375e-02, 1.1967e-01]], grad_fn=<MulBackward0>),
 tensor([[2.0006e-03, 3.6528e+00],
         [5.3375e-02, 1.1967e-01]]))